language: php

php:
  - 7.1
  - 7.2
  - 7.3

sudo: false

before_install:
  - COMPOSER_MEMORY_LIMIT=-1 composer update

script: |
  if [[ $TRAVIS_PHP_VERSION = 7.* ]]; then
      SYMFONY_PHPUNIT_VERSION=6.4 ./vendor/bin/simple-phpunit
  else
      ./vendor/bin/simple-phpunit
  fi
